---
- name: Upgrade apt cache
  apt: update_cache=yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and update_package_cache

- name: Assure pip is not installed via apt.
  apt: name={{ item }} state=absent
  with_items:
    - python-pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install python-setuptools (easy_install)
  apt: name={{ item }} state=latest
  with_items:
    - python-setuptools
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install easy_install via pip.
  command: easy_install pip
  args:
    creates: /usr/local/bin/pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade Virtualenv
  pip: name=virtualenv state=latest

- name: Assure Ansible and required, related packages are installed.
  apt: name={{ item }} state=latest
  with_items:
    - ansible
    - git
    - curl
    - lxde
    - libxml2-dev
    - libxslt1-dev 
    - libxslt-dev 
    - python-dev
    - zlib1g-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Assure services enabled
  service: name="{{ item }}" enabled=true
  with_items:
    - lxdm

- name: Install pip modules
  pip: name="{{ item }}" state=latest
  with_items:
    - httplib2
    - lxml
    - pyvmomi
