---
- name: Upgrade apt cache
  apt: update_cache=yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and update_package_cache

- name: Assure Ansible required related packages are installed.
  apt: name={{ item }} state=latest
  with_items:
    - git
    - curl
    - lxde
    - libxml2-dev
    - libxslt1-dev 
    - libxslt-dev 
    - python-dev
    - zlib1g-dev
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add any additional packages if defined
  apt: name={{ item }} state=latest
  with_items: ansible_additional_packages
  when: ansible_additional_packages is defined

- name: Assure services enabled
  service: name="{{ item }}" enabled=true
  with_items:
    - lxdm

- name: Install pip modules
  pip: name="{{ item }}" state=latest
  with_items:
    - httplib2
    - lxml
    - pyvmomi
    - ansible
